[package]
name = "codegen_underflow"
version = "0.1.0"
authors = ["Marko Mijalkovic <marko.mijalkovic97@gmail.com>"]

build = "build.rs"

[build-dependencies]
diesel_codegen_syntex = "0.7"
syntex = "0.42"
